In [2]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [1]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
#The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). 
#It returns a tuple (or pair), in which the first element contains the input variables for the selected rows, and the second contains the targets.
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:
# Define data loader
#DataLoader, which can split the data into batches of a predefined size while training. 
#It also provides other utilities like shuffling and random sampling of the data
from torch.utils.data import DataLoader
batch_size = 5
Train_dl = DataLoader(train_ds, batch_size, shuffle=True)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [9]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3248, -0.0474, -0.3284],
        [ 0.5638, -0.4717, -0.4410]], requires_grad=True)
Parameter containing:
tensor([-0.2963,  0.0788], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [10]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [11]:
# Import nn.functional
import torch.nn.functional as F

In [12]:
# Define loss function
loss_fn = F.mse_loss

In [13]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(16121.4258, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [14]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in Train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [15]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 261.2181
Epoch [20/100], Loss: 220.5679
Epoch [30/100], Loss: 351.7696
Epoch [40/100], Loss: 265.6008
Epoch [50/100], Loss: 258.4625
Epoch [60/100], Loss: 141.1492
Epoch [70/100], Loss: 108.1234
Epoch [80/100], Loss: 85.0864
Epoch [90/100], Loss: 68.0635
Epoch [100/100], Loss: 9.0222


In [16]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.2473,  72.6485],
        [ 79.5877,  97.0089],
        [122.4195, 136.9993],
        [ 27.7066,  50.4248],
        [ 93.4755, 104.9967],
        [ 58.2473,  72.6485],
        [ 79.5877,  97.0089],
        [122.4195, 136.9993],
        [ 27.7066,  50.4248],
        [ 93.4755, 104.9967],
        [ 58.2473,  72.6485],
        [ 79.5877,  97.0089],
        [122.4195, 136.9993],
        [ 27.7066,  50.4248],
        [ 93.4755, 104.9967]], grad_fn=<AddmmBackward>)

In [17]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [18]:
fit(200, model, loss_fn, opt)

Epoch [10/200], Loss: 47.1278
Epoch [20/200], Loss: 31.7852
Epoch [30/200], Loss: 30.3764
Epoch [40/200], Loss: 33.3291
Epoch [50/200], Loss: 25.2930
Epoch [60/200], Loss: 19.5378
Epoch [70/200], Loss: 22.2039
Epoch [80/200], Loss: 15.1245
Epoch [90/200], Loss: 34.3482
Epoch [100/200], Loss: 17.8636
Epoch [110/200], Loss: 18.6000
Epoch [120/200], Loss: 10.8680
Epoch [130/200], Loss: 22.4854
Epoch [140/200], Loss: 17.1396
Epoch [150/200], Loss: 9.1551
Epoch [160/200], Loss: 9.7208
Epoch [170/200], Loss: 18.0437
Epoch [180/200], Loss: 13.0445
Epoch [190/200], Loss: 7.4452
Epoch [200/200], Loss: 11.1073


#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 